language: python
python:
  - "3.6"

dist: trusty
sudo: required

# command to install dependencies
install:
  install:
  # Update docker-engine using Ubuntu 'trusty' apt repo
  - >
    curl -sSL "https://get.docker.com/gpg" |
     sudo -E apt-key add -
  - >
    echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" |
     sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - >
    sudo apt-get -o Dpkg::Options::="--force-confdef" \
     -o Dpkg::Options::="--force-confold" --assume-yes install docker-engine
  - docker version
  # Update docker-compose via pip
  - sudo pip install docker-compose
  - docker-compose version

before_script:
  - docker-compose up --build -d

script:
  - ./test.sh

after_script:
  - docker-compose down

addons:
  sonarcloud:
    organization: "dean-kim-github"
    token:
      secure: "gw3yN07K7+bgd4HYCYoK6yhah44Ggy29uRmEA0jbwqWSQ5iYfiGutNTV935CTsrZdQnJ+OTDxl9cLqAn3yEsvnZSE5vTIWILQbSysZsVwkUlEIeWnxc5tIFgF/zMsutXYQfqkmLHa0gm5PKKIAGUcF7YLO2SD6WPvE0kiYZqRQgCI9ZcvEbmma0Lqve9+TVNjSqrWpch8OHx1xwAATWmiVJK2qKig/r8YZfDcv52NqcqqWC8rwtzQKM/BEE2tlvDQA/jqH48gJXmpkI4Xy7+JyKV0MzyWdCNQxGa9lGGvwa5XXegObGX5rUJU3Eu+7PdtZIlZk5PD/Uq89kzgpUFZnwpiXDosJ9kaREPPq2IiuXs11Ylalyhqq20iRAbltrVQGD5vQACa642pAEtpEjkgTHELbjWMiJ7l/4xLYjPu6HlEzpYcM3+ctu2zkBw8tNKXU/Jelz4Ki3pcwf3PZxJeGEIJshRirDKmNErD5dSs7Eq+0qRbE/oftUMTkTdPnLBEhE//lR/JLWTCHXHtV8yxsfKEcYC0jRMp6UMq860HpO1SmJV1neHrgoqzlPX1obfemIvXQrmXa4VCkzC1hTK7+ZYGg82Dkjl9vna1jVd/Si+N39cJd0/Eo18HW+SGY1uNVPGdmSfyTAV84MPJd2MMRiQW+4E+6V6/lp5mi8rNwU="
script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'


