version: '2'

services:

  refrigeratordb:
    image: "postgres:9.6.1"
    container_name: refrigeratordb
    ports:
     - "5432"
    environment:
     POSTGRES_PASSWORD: "sodwkdrh"
     POSTGRES_USER: "refrigerator"
     POSTGRES_DB: "refrigeratordb"

  refrigerator:
    build: .
    container_name: refrigeratormanager
    ports:
     - "3000:8000"
    depends_on:
     - refrigeratordb
    links:
     - refrigeratordb
    volumes:
     - .:/var/www/refrigerator
    entrypoint: /bin/sh
    stdin_open: true  # means -i option in docker run
    tty: true         # means -t option in docker run