version: '2'

services:

  refrigeratordb:
    image: "postgres:9.6.1"
    container_name: refrigeratordb
    expose:
     - "5432"
    environment:
     POSTGRES_PASSWORD: "sodwkdrh"
     POSTGRES_USER: "refrigerator"
     POSTGRES_DB: "refrigeratordb"

  refrigerator:
    build: .
    container_name: refrigeratormanager
    expose:
     - "8000"
    depends_on:
     - refrigeratordb
    links:
     - refrigeratordb
    volumes:
     - .:/var/www/refrigerator
    entrypoint: /bin/sh
    stdin_open: true  # means -i option in docker run
    tty: true         # means -t option in docker run

  nginx:
    restart: always
    build: ./nginx/
    ports:
     - "80:80"
    volumes_from:
     - refrigerator
    links:
     - refrigerator:refrigerator